// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testpowerstate.proxies;

public class NativeAppContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject nativeAppContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestPowerState.NativeAppContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PowerStateString("PowerStateString"),
		PowerStateEnum("PowerStateEnum");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public NativeAppContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected NativeAppContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject nativeAppContextMendixObject)
	{
		if (nativeAppContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, nativeAppContextMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.nativeAppContextMendixObject = nativeAppContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static testpowerstate.proxies.NativeAppContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testpowerstate.proxies.NativeAppContext(context, mendixObject);
	}

	public static testpowerstate.proxies.NativeAppContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testpowerstate.proxies.NativeAppContext.initialize(context, mendixObject);
	}

	/**
	 * @return value of PowerStateString
	 */
	public final java.lang.String getPowerStateString()
	{
		return getPowerStateString(getContext());
	}

	/**
	 * @param context
	 * @return value of PowerStateString
	 */
	public final java.lang.String getPowerStateString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PowerStateString.toString());
	}

	/**
	 * Set value of PowerStateString
	 * @param powerstatestring
	 */
	public final void setPowerStateString(java.lang.String powerstatestring)
	{
		setPowerStateString(getContext(), powerstatestring);
	}

	/**
	 * Set value of PowerStateString
	 * @param context
	 * @param powerstatestring
	 */
	public final void setPowerStateString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String powerstatestring)
	{
		getMendixObject().setValue(context, MemberNames.PowerStateString.toString(), powerstatestring);
	}

	/**
	 * Get value of PowerStateEnum
	 * @param powerstateenum
	 */
	public final testpowerstate.proxies.PowerState getPowerStateEnum()
	{
		return getPowerStateEnum(getContext());
	}

	/**
	 * @param context
	 * @return value of PowerStateEnum
	 */
	public final testpowerstate.proxies.PowerState getPowerStateEnum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.PowerStateEnum.toString());
		if (obj == null) {
			return null;
		}
		return testpowerstate.proxies.PowerState.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of PowerStateEnum
	 * @param powerstateenum
	 */
	public final void setPowerStateEnum(testpowerstate.proxies.PowerState powerstateenum)
	{
		setPowerStateEnum(getContext(), powerstateenum);
	}

	/**
	 * Set value of PowerStateEnum
	 * @param context
	 * @param powerstateenum
	 */
	public final void setPowerStateEnum(com.mendix.systemwideinterfaces.core.IContext context, testpowerstate.proxies.PowerState powerstateenum)
	{
		if (powerstateenum != null) {
			getMendixObject().setValue(context, MemberNames.PowerStateEnum.toString(), powerstateenum.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.PowerStateEnum.toString(), null);
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return nativeAppContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testpowerstate.proxies.NativeAppContext that = (testpowerstate.proxies.NativeAppContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
