// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("9685b07d-5959-420c-9762-7a0e559c82f3"),
	startsWith("4beaac0a-c0ee-4695-b8e3-4eb1c657dcb6"),
	endsWith("efec2270-01a2-4e28-8170-e9b147d55131"),
	between("9db0fbb9-f5d4-401c-897d-22facc848252"),
	greater("2dc44fa3-f57e-4352-8830-e5e1cb69ceb1"),
	greaterEqual("2346fc72-67f3-4b9b-acd1-91706f2709d1"),
	equal("178e702e-fd5c-4cef-8a5f-77adf64c1e9d"),
	notEqual("ef06f1f3-dc92-4563-96a1-1b82e315d7c3"),
	smaller("591374f8-f6a1-4fe3-a567-b1534fb66b08"),
	smallerEqual("3231d013-35c7-4c4d-9339-3d6fcab50fe5"),
	empty("bbdf47ce-863c-409d-b579-83acde5d44f0"),
	notEmpty("1ef7d53c-d6fa-4232-b5ec-85a2b2dc2395");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
