// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("7054f8a8-a86a-4e31-914b-aa73504d3478"),
	denied("5c53e22a-c433-4243-99f2-aed15824c441"),
	limited("d6352674-5ed7-4381-a609-4ff5950e491d"),
	granted("efa1bc3a-9261-4a0c-8f8e-0f5d794fe5ec"),
	blocked("4ec859b7-7b5b-49f4-94f6-8fc971a7f1b2");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
