// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("073bc7f9-c2a2-4596-884d-7ca93876db02"),
	low("0520d90d-c486-4eba-b232-57441cf03b97"),
	medium("1b2e76a8-0116-4330-9264-cba383a15d43"),
	high("eba72a18-8f57-494d-ba00-47b2f16712e3"),
	custom("00200e91-2005-4a42-9096-18ce630f8acb");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
