// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("9ad4fa99-5b8e-4e31-b255-cb3d2faee08b"),
	low("8673c9d3-1271-4866-9a39-1477df214b17"),
	medium("a00eda2c-c796-4304-b158-d74981e3579b"),
	high("e7f23165-0cd8-4d74-973b-93219fb7049d"),
	custom("608c9ad6-4894-4157-9309-c5d2843df829");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
