// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum StatusBarStyle
{
	DefaultStyle("e3f73ddf-8f3a-4364-8296-1129ed181629"),
	LightContentStyle("fe01234c-dd5d-4085-a6a9-c3506e244b06"),
	DarkContentStyle("2e1d01b5-d030-474d-bf1e-b2684080043a");

	private final java.lang.String i18nCaptionKey;
	
	private StatusBarStyle(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
