// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum StatusBarHideShowAnimation
{
	none("73915555-1976-46fc-9b55-1a63d736c24c"),
	fade("67c5b9dc-4b5a-42e7-ace7-ab05a544c46f"),
	slide("2d7e880b-19cd-4486-883f-1422d30f407d");

	private final java.lang.String i18nCaptionKey;
	
	private StatusBarHideShowAnimation(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
