// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum StatusBarStyle
{
	DefaultStyle("f3466f16-925c-4e57-a1d7-df1a51f8f409"),
	LightContentStyle("8b322f66-ddd1-4d7b-b3e9-896c391c3b12"),
	DarkContentStyle("e9428d6b-30be-489e-b119-22e24982fa80");

	private final java.lang.String i18nCaptionKey;
	
	private StatusBarStyle(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
